path: /Users/banqingyuan/Documents/repo/yolo-model-training/artifacts/datasets/self-build-v3/v3
train: images/train
val: images/val
test: images/test
names:
  0: RA
  1: R2
  2: R3
  3: R4
  4: R5
  5: R6
  6: R7
  7: R8
  8: R9
  9: R10
  10: RJ
  11: RQ
  12: RK
  13: BA
  14: B2
  15: B3
  16: B4
  17: B5
  18: B6
  19: B7
  20: B8
  21: B9
  22: B10
  23: BJ
  24: BQ
  25: BK
  26: D
  27: X

